# Tên của quy trình, sẽ hiển thị trong tab "Actions" của repo
name: Generate ADB Shell Script

# Định nghĩa sự kiện kích hoạt quy trình
on:
  push:
    branches:
      # Chạy trên nhánh 'main'. Thay đổi nếu bạn dùng nhánh khác (ví dụ: 'master')
      - main
    paths:
      # CHỈ chạy khi có sự thay đổi trong tệp này
      - 'debug_adb.py'

# Định nghĩa các công việc cần thực hiện
jobs:
  build-and-commit:
    # Sử dụng một máy ảo Ubuntu mới nhất để chạy
    runs-on: ubuntu-latest

    # Các bước thực hiện công việc
    steps:
      # Bước 1: Checkout mã nguồn từ repo về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Bạn có thể chọn phiên bản Python bạn muốn

      # (Tùy chọn) Nếu script của bạn có thư viện cần cài đặt, hãy thêm bước này
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Bước 3: Chạy script Python và lưu kết quả ra tệp auto_script.sh
      - name: Run Python script to generate the shell script
        # Quan trọng: Thay 'debug_adb.py' bằng đường dẫn chính xác tới tệp của bạn nếu nó nằm trong thư mục con
        run: python debug_adb.py > auto_script.sh

      # Bước 4: Tự động commit và push tệp auto_script.sh đã được tạo
      - name: Commit and push updated script
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Tin nhắn cho commit tự động
          commit_message: 'Automated: Update auto_script.sh'
          
          # Tên tệp cần commit. Chỉ commit tệp này.
          file_pattern: 'auto_script.sh'
          
          # Thông tin người commit (Bot)
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
